// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: images.sql

package sqlc

import (
	"context"
)

const countImages = `-- name: CountImages :one
SELECT COUNT(*) FROM images
`

func (q *Queries) CountImages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countImages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingImages = `-- name: CountPendingImages :one
SELECT COUNT(*) FROM images
WHERE is_finished = FALSE
`

func (q *Queries) CountPendingImages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingImages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createImage = `-- name: CreateImage :one
INSERT INTO images (path, original_filename)
VALUES (?, ?)
RETURNING id, path, original_filename, ingested_at, completed_stages, is_finished
`

type CreateImageParams struct {
	Path             string  `json:"path"`
	OriginalFilename *string `json:"original_filename"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, createImage, arg.Path, arg.OriginalFilename)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.OriginalFilename,
		&i.IngestedAt,
		&i.CompletedStages,
		&i.IsFinished,
	)
	return i, err
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM images
WHERE id = ?
`

func (q *Queries) DeleteImage(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteImage, id)
	return err
}

const getImage = `-- name: GetImage :one
SELECT id, path, original_filename, ingested_at, completed_stages, is_finished FROM images
WHERE id = ?
`

func (q *Queries) GetImage(ctx context.Context, id int64) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImage, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.OriginalFilename,
		&i.IngestedAt,
		&i.CompletedStages,
		&i.IsFinished,
	)
	return i, err
}

const getImageByPath = `-- name: GetImageByPath :one
SELECT id, path, original_filename, ingested_at, completed_stages, is_finished FROM images
WHERE path = ?
`

func (q *Queries) GetImageByPath(ctx context.Context, path string) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImageByPath, path)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.OriginalFilename,
		&i.IngestedAt,
		&i.CompletedStages,
		&i.IsFinished,
	)
	return i, err
}

const listImages = `-- name: ListImages :many
SELECT id, path, original_filename, ingested_at, completed_stages, is_finished FROM images
ORDER BY id
`

func (q *Queries) ListImages(ctx context.Context) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.OriginalFilename,
			&i.IngestedAt,
			&i.CompletedStages,
			&i.IsFinished,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesNotFinished = `-- name: ListImagesNotFinished :many
SELECT id, path, original_filename, ingested_at, completed_stages, is_finished FROM images
WHERE is_finished = FALSE
ORDER BY completed_stages ASC, id ASC
LIMIT ?
`

func (q *Queries) ListImagesNotFinished(ctx context.Context, limit int64) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImagesNotFinished, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.OriginalFilename,
			&i.IngestedAt,
			&i.CompletedStages,
			&i.IsFinished,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImageCompletionStatus = `-- name: UpdateImageCompletionStatus :exec
UPDATE images
SET completed_stages = ?,
    is_finished = ?
WHERE id = ?
`

type UpdateImageCompletionStatusParams struct {
	CompletedStages *int64 `json:"completed_stages"`
	IsFinished      *bool  `json:"is_finished"`
	ID              int64  `json:"id"`
}

func (q *Queries) UpdateImageCompletionStatus(ctx context.Context, arg UpdateImageCompletionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateImageCompletionStatus, arg.CompletedStages, arg.IsFinished, arg.ID)
	return err
}
