// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: images.sql

package sqlc

import (
	"context"
)

const countImages = `-- name: CountImages :one
SELECT COUNT(*) FROM images
`

func (q *Queries) CountImages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countImages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createImage = `-- name: CreateImage :one
INSERT INTO images (sha256, filename)
VALUES (?, ?)
ON CONFLICT(sha256) DO UPDATE SET filename = excluded.filename
RETURNING sha256, filename, ingested_at
`

type CreateImageParams struct {
	Sha256   string `json:"sha256"`
	Filename string `json:"filename"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, createImage, arg.Sha256, arg.Filename)
	var i Image
	err := row.Scan(&i.Sha256, &i.Filename, &i.IngestedAt)
	return i, err
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM images
WHERE sha256 = ?
`

func (q *Queries) DeleteImage(ctx context.Context, sha256 string) error {
	_, err := q.db.ExecContext(ctx, deleteImage, sha256)
	return err
}

const getImage = `-- name: GetImage :one
SELECT sha256, filename, ingested_at FROM images
WHERE sha256 = ?
`

func (q *Queries) GetImage(ctx context.Context, sha256 string) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImage, sha256)
	var i Image
	err := row.Scan(&i.Sha256, &i.Filename, &i.IngestedAt)
	return i, err
}

const getImageByFilename = `-- name: GetImageByFilename :one
SELECT sha256, filename, ingested_at FROM images
WHERE filename = ?
`

func (q *Queries) GetImageByFilename(ctx context.Context, filename string) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImageByFilename, filename)
	var i Image
	err := row.Scan(&i.Sha256, &i.Filename, &i.IngestedAt)
	return i, err
}

const listImages = `-- name: ListImages :many
SELECT sha256, filename, ingested_at FROM images
ORDER BY filename
`

func (q *Queries) ListImages(ctx context.Context) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(&i.Sha256, &i.Filename, &i.IngestedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesNotFinished = `-- name: ListImagesNotFinished :many
SELECT sha256, filename, ingested_at FROM images
ORDER BY filename ASC
LIMIT ?
`

func (q *Queries) ListImagesNotFinished(ctx context.Context, limit int64) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImagesNotFinished, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(&i.Sha256, &i.Filename, &i.IngestedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
