// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type Annotation struct {
	ID          int64      `json:"id"`
	ImageSha256 string     `json:"image_sha256"`
	Username    string     `json:"username"`
	StageIndex  int64      `json:"stage_index"`
	OptionValue string     `json:"option_value"`
	AnnotatedAt *time.Time `json:"annotated_at"`
}

type Image struct {
	Sha256     string     `json:"sha256"`
	Filename   string     `json:"filename"`
	IngestedAt *time.Time `json:"ingested_at"`
}
