// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type Annotation struct {
	ID          int64      `json:"id"`
	ImageID     int64      `json:"image_id"`
	Username    string     `json:"username"`
	StageIndex  int64      `json:"stage_index"`
	OptionValue string     `json:"option_value"`
	AnnotatedAt *time.Time `json:"annotated_at"`
}

type Image struct {
	ID               int64      `json:"id"`
	Path             string     `json:"path"`
	OriginalFilename *string    `json:"original_filename"`
	IngestedAt       *time.Time `json:"ingested_at"`
	CompletedStages  *int64     `json:"completed_stages"`
	IsFinished       *bool      `json:"is_finished"`
}
